In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [3]:
#Basic of NumPy
#Numpy creating arrays
#numpy Array Indexinng
#Array Slicing
#copy vs view
#shape vs reshape
#Array iterating
#Array sort
#Array join
#Array split
#Array filter
#Array Search
#Numpy methods:reshape(),MAX(),MIN(),ARGMAX(),ARGMIN()
#Random function:rand(),randn(),randint()

In [7]:
#Creating_Arrays


In [9]:
list=[1,2,3,4,5,6,7,8,9,10]
array1=np.array(list)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [12]:
np.linspace(1,2,100,retstep=True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [13]:
np.random.rand(10)

array([0.22638609, 0.45321338, 0.20582676, 0.61972433, 0.87588151,
       0.19370583, 0.47664571, 0.86529895, 0.97587241, 0.82764538])

In [16]:
np.random.randint(0,3,50)

array([0, 1, 1, 1, 0, 2, 0, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 0, 2, 1, 0, 2,
       1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 1, 0, 1, 1, 0, 2,
       2, 1, 0, 1, 0, 2])

In [17]:
np.random.randn(20,4)

array([[ 0.47514615,  1.20501068,  0.95862796,  0.85749459],
       [ 0.70795874, -1.34791891,  1.12629203, -2.00513798],
       [ 1.21451095, -0.88673851,  0.49746306,  1.65187178],
       [ 0.45468236,  1.41282043, -0.57812698, -0.09917383],
       [-0.65184052, -2.0602138 , -0.19722234,  0.5725121 ],
       [ 0.56388447, -0.23754564, -0.15629183,  0.15659675],
       [ 0.41774267, -0.35343598,  0.08575985, -0.89626151],
       [ 0.18130957, -0.47481352,  0.51565303, -0.73286574],
       [-0.20493896, -0.7801676 , -1.47667646,  0.73408474],
       [ 2.0806889 ,  1.62763627, -0.09219411,  1.1805593 ],
       [-1.66901099,  0.19651409, -0.10009938,  0.59734273],
       [-0.0371764 , -0.75358569,  0.08803383,  1.46943713],
       [ 0.13144749,  0.41933362, -0.83043377,  0.37963506],
       [-0.9082234 , -0.40976014,  0.60000175, -0.35024846],
       [-0.14001792, -0.01040896,  1.07914965,  1.35501066],
       [ 2.50070427,  1.83314888, -0.04373835, -0.8414639 ],
       [ 1.79613435, -1.

In [24]:
array2=np.arange(1,101)
array2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
array2.dtype

dtype('int32')

In [25]:
array2.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
#ones function
array3=np.ones((4,4))
array3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
array4=np.random.randint(1,10,50)
array4


array([2, 9, 5, 3, 2, 3, 7, 6, 6, 3, 5, 2, 6, 5, 3, 5, 5, 3, 4, 5, 5, 9,
       8, 4, 5, 9, 2, 1, 4, 1, 2, 5, 9, 5, 8, 3, 7, 7, 7, 1, 2, 5, 7, 9,
       6, 9, 8, 8, 8, 8])

In [37]:
modulus=array4 % 2==0
modulus

array([ True, False, False, False,  True, False, False,  True,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True,  True,  True,  True])

In [38]:
array5=np.arange(1,51)
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [39]:
sum=array4+array5
sum

array([ 3, 11,  8,  7,  7,  9, 14, 14, 15, 13, 16, 14, 19, 19, 18, 21, 22,
       21, 23, 25, 26, 31, 31, 28, 30, 35, 29, 29, 33, 31, 33, 37, 42, 39,
       43, 39, 44, 45, 46, 41, 43, 47, 50, 53, 51, 55, 55, 56, 57, 58])

In [41]:
sub=array4-array5
sub

array([  1,   7,   2,  -1,  -3,  -3,   0,  -2,  -3,  -7,  -6, -10,  -7,
        -9, -12, -11, -12, -15, -15, -15, -16, -13, -15, -20, -20, -17,
       -25, -27, -25, -29, -29, -27, -24, -29, -27, -33, -30, -31, -32,
       -39, -39, -37, -36, -35, -39, -37, -39, -40, -41, -42])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
arr6=np.arange(2,10)
x=arr6.view()
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
y=np.where(arr6==8)
y

(array([6], dtype=int64),)

In [51]:
sorting=np.sort(sub)
sorting

array([-42, -41, -40, -39, -39, -39, -39, -37, -37, -36, -35, -33, -32,
       -31, -30, -29, -29, -29, -27, -27, -27, -25, -25, -24, -20, -20,
       -17, -16, -15, -15, -15, -15, -13, -12, -12, -11, -10,  -9,  -7,
        -7,  -6,  -3,  -3,  -3,  -2,  -1,   0,   1,   2,   7])